stages:
  - test

image:
  name: python:3.8  # Escolha a versão desejada do Python

test:
  stage: test
  script:
    # Adiciona o repositório e instala a versão 110 do Google Chrome
    - apt-get update && apt-get install -y wget curl unzip
    - wget http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_100.0.4896.127-1_amd64.deb
    - apt-get -y install ./google-chrome-stable_100.0.4896.127-1_amd64.deb
    - google-chrome-stable --version

    # Instala o ChromeDriver versão 110
    - wget "https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip" -O chromedriver.zip
    - unzip -d chromedriver chromedriver.zip
    - chmod +x chromedriver/chromedriver
    - mv chromedriver/chromedriver /usr/local/bin/

    # Exibe as versões instaladas
    - google-chrome-stable --version
    - chromedriver --version

    # Define as variáveis de ambiente para o ChromeDriver
    - export CHROME_BIN=/usr/bin/google-chrome-stable
    - export DISPLAY=:99.0

    # Configuração adicional do ChromeDriver
    - chromedriver --no-sandbox --disable-dev-shm-usage &
    - pip install -U pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install selenium==4.9.0
    - robot teste3.robot
    - pkill -f chromedriver