name: Testes com Robot Framework e SeleniumLibrary

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Configurar ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=121.0.6167.85
        curl -o /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chromedriver-linux64.zip
        ls
        unzip /tmp/chromedriver-linux64.zip -d $HOME
        sudo mv $HOME/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Executar testes
      run: |
        ls
        robot -d results teste2.robot
        cp results/output.xml $GITHUB_WORKSPACE/results/
        cp results/log.html $GITHUB_WORKSPACE/results/
        cp results/report.html $GITHUB_WORKSPACE/results
