name: Testes com Robot Framework e SeleniumLibrary

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_reports_dir: 'robot_tests'

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: robot-reports
        path: |
          /opt/robotframework/reports/output.xml
          /opt/robotframework/reports/log.html
          /opt/robotframework/reports/report.html
