name: Testes com Robot Framework e SeleniumLibrary

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0

    - name: Executar testes
      run: |
        robot -d results teste2.robot
        cp results/output.xml $GITHUB_WORKSPACE/results/
        cp results/log.html $GITHUB_WORKSPACE/results/
        cp results/report.html $GITHUB_WORKSPACE/results
